name: build_deploy_aks

on:
  push:
    branches:
      - on-prem

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Log in to ACR
        run: |
          echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ secrets.ACR_REGISTRY }} -u ${{ secrets.ACR_USERNAME }} --password-stdin

      - name: Create .env file from secret
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: Build and Push Image with Build Args
        run: |
          docker build \
            --build-arg AUTH_TRUST_HOST=${{ secrets.AUTH_TRUST_HOST }} \
            --build-arg AUTH_URL=${{ secrets.AUTH_URL }} \
            --build-arg DATABASE_URI=${{ secrets.DATABASE_URI }} \
            --build-arg EMAIL_USER=${{ secrets.EMAIL_USER }} \
            --build-arg NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }} \
            --build-arg NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }} \
            --build-arg NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=${{ secrets.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY }} \
            --build-arg NEXT_PUBLIC_SERVER_URL=${{ secrets.NEXT_PUBLIC_SERVER_URL }} \
            --build-arg PAYLOAD_SECRET=${{ secrets.PAYLOAD_SECRET }} \
            --build-arg RESEND_API_KEY=${{ secrets.RESEND_API_KEY }} \
            --build-arg S3_ACCESS_KEY_ID=${{ secrets.S3_ACCESS_KEY_ID }} \
            --build-arg S3_BUCKET=${{ secrets.S3_BUCKET }} \
            --build-arg S3_REGION=${{ secrets.S3_REGION }} \
            --build-arg S3_SECRET_ACCESS_KEY=${{ secrets.S3_SECRET_ACCESS_KEY }} \
            -t ${{ secrets.ACR_REGISTRY }}/unilag-intern:${{ github.sha }} .
          docker push ${{ secrets.ACR_REGISTRY }}/unilag-intern:${{ github.sha }}

  update-helm:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Helm charts repository
        uses: actions/checkout@v3
        with:
          repository: Koonage-infotech/helm-charts
          token: ${{ secrets.PAT_TOKEN }}

      - name: Update image tag in values.yaml
        run: |
          sed -i 's|tag: .*|tag: "'"${{ github.sha }}"'"|' unilag-intern/values.yaml

      - name: Commit and push changes
        env:
          GIT_COMMITTER_NAME: "GitHub Actions"
          GIT_COMMITTER_EMAIL: "github-actions@github.com"
        run: |
          git config --global user.name "$GIT_COMMITTER_NAME"
          git config --global user.email "$GIT_COMMITTER_EMAIL"
          git add unilag-intern/values.yaml
          git commit -m "Update unilag-intern image tag to ${{ github.sha }}" || echo "No changes to commit"
          git push origin main || echo "No changes to push"
